import Footer from './Components/Footer'
import Navbar from './Components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Next Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <nav>
          <Navbar></Navbar>
        </nav>
        <main>  {children}</main>

      </body>
    </html>
  )
}
